[package]
name = "ya"
authors = ["kikeg"]
version = "0.2.0"
edition = "2021"
rust-version = "1.70.0"
license = "Apache-2.0"
description = "Yet Another YAML parser in pure Rust"

[dependencies]
winnow = { version = "1.0", features = ["simd"] }

[dev-dependencies]
criterion = "0.8.2"
rstest = "0.26.1"

[[bench]]
name = "benchmark"
harness = false
